import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
 <input name='search' type='search' placeholder='search' />
 <input type='submit' value="search" />



 <h2>add a suggestion</h2>
 <label htmlFor='word'>word</label>
 <input type="text" name='word' placeholder="word" />
<label htmlFor="description"></label>
 <textarea id="description" >

 </textarea>

 <input type='submit' value="add word" />
 
      <main className="flex ">
        <h1 className='text-2xl'>ikalanga dictionary</h1> 

        </main>
      

    </div>
  )
}

export default Home
